# Generated by Django 4.2.6 on 2023-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truufrend', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
