# Generated by Django 4.2.6 on 2023-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truufrend', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
