# Generated by Django 4.2.6 on 2023-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truufrend', '0005_sos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='challenges',
            field=models.TextField(choices=[('Anxiety', 'Anxiety'), ('Motivation', 'Motivation'), ('Confidence', 'Confidence'), ('Sleep', 'Sleep'), ('Depression', 'Depression'), ('Work Stress', 'Work Stress'), ('Relationships', 'Relationships'), ('Exam stress', 'Exam stress'), ('Pregnancy', 'Pregnancy'), ('Loss', 'Loss'), ('LGBTQ+', 'LGBTQ+'), ('Low Energy', 'Low Energy'), ('Self Esteem', 'Self Esteem'), ('Loneliness', 'Loneliness'), ('Trauma', 'Trauma'), ('Health issues', 'Health issues')]),
        ),
    ]
