# Generated by Django 4.2.6 on 2023-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truufrend', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, choices=[('13-17 years old', '13-17 years old'), ('18 Years and old', '18 Years and old')], null=True),
        ),
    ]
